import { getTranslations } from "next-intl/server";
import { ArrowRight, Check, MapPin, ShieldCheck, TrendingUp, Wheat } from "lucide-react";
import { Link } from "@/i18n/navigation";

const marketPulse = [42, 48, 44, 57, 53, 67, 72];

export default async function Home() {
  const t = await getTranslations("home");

  return (
    <div className="-mx-4 overflow-hidden sm:-mx-6 lg:-mx-8">
      <section className="relative border-b border-border/70 px-4 pb-20 pt-10 sm:px-6 lg:px-8 lg:pb-28 lg:pt-16">
        <div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[0.9fr_1.1fr] lg:items-center">
          <div className="max-w-2xl">
            <p className="mb-6 flex items-center gap-2 text-sm font-semibold text-primary"><span className="h-px w-8 bg-accent" />{t("badge")}</p>
            <h1 className="font-display text-5xl leading-[0.98] tracking-tight text-foreground sm:text-6xl lg:text-7xl">{t("headline")}<span className="block text-primary">{t("headlineAccent")}</span></h1>
            <p className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground sm:text-xl">{t("subtitle")}</p>
            <div className="mt-9 flex flex-wrap gap-3"><Link href="/register" className="inline-flex h-11 items-center gap-2 rounded-sm bg-primary px-5 text-sm font-semibold text-primary-foreground transition-transform hover:-translate-y-0.5">{t("ctaPutLot")} <ArrowRight className="h-4 w-4" /></Link><Link href="/lots" className="inline-flex h-11 items-center gap-2 rounded-sm border border-primary/30 bg-transparent px-5 text-sm font-semibold text-primary hover:bg-secondary">{t("ctaBrowse")}</Link></div>
            <div className="mt-9 flex flex-wrap gap-x-6 gap-y-3 border-t border-border/70 pt-5 text-sm text-muted-foreground"><span className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-primary" />{t("trustIdentity")}</span><span className="flex items-center gap-2"><MapPin className="h-4 w-4 text-primary" />{t("trustMandi")}</span></div>
          </div>
          <div className="market-board market-grid relative overflow-hidden border border-primary/20 bg-card p-5 sm:p-7">
            <div className="flex items-start justify-between border-b border-border/70 pb-5"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-muted-foreground">{t("boardLabel")}</p><h2 className="mt-2 font-display text-3xl text-foreground">{t("boardSubtitle")}</h2></div><span className="flex items-center gap-1.5 text-sm font-semibold text-primary"><span className="h-2 w-2 rounded-full bg-primary" />{t("boardToday")}</span></div>
            <div className="price-reveal py-7"><div className="flex items-end justify-between gap-4"><p className="text-sm text-muted-foreground">{t("boardRangeLabel")}</p><span className="text-xs text-muted-foreground">{t("boardRangeUpdate")}</span></div><div className="mt-1 flex flex-wrap items-end gap-3"><span className="font-display text-5xl text-foreground sm:text-6xl">₹2,480</span><span className="mb-2 text-sm font-semibold text-primary">/ quintal <span className="ml-2 text-clay">↑ 4.8%</span></span></div><div className="mt-6 flex h-10 items-end gap-1 border-b border-border/70 pb-1">{marketPulse.map((height, index) => <span key={index} className="flex-1 bg-accent/70 transition-all first:bg-primary last:bg-primary" style={{ height: `${height}%` }} />)}</div><div className="mt-2 flex justify-between text-xs text-muted-foreground"><span>{t("boardMovement")}</span><span>{t("boardMovementRange")}</span></div></div>
            <div className="grid gap-px border-y border-border/70 bg-border/70 sm:grid-cols-3"><div className="bg-card px-4 py-4"><p className="text-xs text-muted-foreground">{t("boardFarmerAsk")}</p><p className="mt-1 text-lg font-bold">₹2,350</p></div><div className="bg-card px-4 py-4"><p className="text-xs text-muted-foreground">{t("boardBuyerRange")}</p><p className="mt-1 text-lg font-bold">₹2.4–2.52k</p></div><div className="bg-card px-4 py-4"><p className="text-xs text-muted-foreground">{t("boardAvailable")}</p><p className="mt-1 text-lg font-bold">18 quintal</p></div></div>
            <div className="mt-5 flex items-center justify-between text-sm"><span className="flex items-center gap-2 text-muted-foreground"><Wheat className="h-4 w-4 text-accent" />{t("boardGrade")}</span><Link href="/lots" className="font-semibold text-primary hover:text-clay">{t("boardBrowse")} <ArrowRight className="ml-1 inline h-4 w-4" /></Link></div>
          </div>
        </div>
      </section>
      <section className="border-b border-border/70 bg-secondary/40 px-4 py-16 sm:px-6 lg:px-8 lg:py-20"><div className="mx-auto max-w-7xl"><div className="grid gap-10 lg:grid-cols-[0.7fr_1.3fr] lg:items-end"><div><p className="text-sm font-semibold text-primary">{t("twoSidesLabel")}</p><h2 className="mt-3 max-w-md font-display text-4xl leading-tight sm:text-5xl">{t("twoSidesHeadline")}</h2></div><p className="max-w-xl text-lg leading-8 text-muted-foreground">{t("twoSidesDesc")}</p></div><div className="mt-12 grid gap-5 md:grid-cols-2"><div className="bg-primary p-7 text-primary-foreground sm:p-9"><div className="flex items-center justify-between"><h3 className="font-display text-3xl">{t("forFarmers")}</h3><Wheat className="h-7 w-7 text-accent" /></div><p className="mt-4 text-primary-foreground/75">{t("forFarmersDesc")}</p><ul className="mt-7 space-y-3 text-sm text-primary-foreground/90"><li className="flex gap-3"><Check className="h-5 w-5 shrink-0 text-accent" />{t("farmerPts1")}</li><li className="flex gap-3"><Check className="h-5 w-5 shrink-0 text-accent" />{t("farmerPts2")}</li><li className="flex gap-3"><Check className="h-5 w-5 shrink-0 text-accent" />{t("farmerPts3")}</li></ul><Link href="/register" className="mt-8 inline-flex items-center gap-2 font-semibold text-accent">{t("startSelling")} <ArrowRight className="h-4 w-4" /></Link></div><div className="border border-border/70 bg-card p-7 sm:p-9"><div className="flex items-center justify-between"><h3 className="font-display text-3xl">{t("forBuyers")}</h3><TrendingUp className="h-7 w-7 text-accent" /></div><p className="mt-4 text-muted-foreground">{t("forBuyersDesc")}</p><ul className="mt-7 space-y-3 text-sm"><li className="flex gap-3"><Check className="h-5 w-5 shrink-0 text-accent" />{t("buyerPts1")}</li><li className="flex gap-3"><Check className="h-5 w-5 shrink-0 text-accent" />{t("buyerPts2")}</li><li className="flex gap-3"><Check className="h-5 w-5 shrink-0 text-accent" />{t("buyerPts3")}</li></ul><Link href="/register" className="mt-8 inline-flex items-center gap-2 font-semibold text-primary">{t("startBuying")} <ArrowRight className="h-4 w-4" /></Link></div></div></div></section>
      <section className="px-4 py-16 sm:px-6 lg:px-8 lg:py-20"><div className="mx-auto max-w-7xl"><p className="text-sm font-semibold text-primary">{t("howWorksLabel")}</p><div className="mt-8 grid gap-0 border-y border-border/70 md:grid-cols-3"><div className="border-b border-border/70 py-7 md:border-b-0 md:border-r md:px-8 md:first:pl-0"><span className="font-display text-4xl text-accent">01</span><h3 className="mt-5 text-lg font-bold">{t("step1Title")}</h3><p className="mt-2 max-w-xs leading-7 text-muted-foreground">{t("step1Desc")}</p></div><div className="border-b border-border/70 py-7 md:border-b-0 md:border-r md:px-8"><span className="font-display text-4xl text-accent">02</span><h3 className="mt-5 text-lg font-bold">{t("step2Title")}</h3><p className="mt-2 max-w-xs leading-7 text-muted-foreground">{t("step2Desc")}</p></div><div className="border-b border-border/70 py-7 md:border-b-0 md:px-8 md:last:pr-0"><span className="font-display text-4xl text-accent">03</span><h3 className="mt-5 text-lg font-bold">{t("step3Title")}</h3><p className="mt-2 max-w-xs leading-7 text-muted-foreground">{t("step3Desc")}</p></div></div></div></section>
      <section className="bg-primary px-4 py-14 text-primary-foreground sm:px-6 lg:px-8 lg:py-18"><div className="mx-auto flex max-w-7xl flex-col gap-8 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-semibold text-accent">{t("ctaBadge")}</p><h2 className="mt-3 max-w-2xl font-display text-4xl leading-tight sm:text-5xl">{t("ctaHeadline")}</h2></div><div className="flex shrink-0 flex-wrap gap-3"><Link href="/register" className="inline-flex h-11 items-center gap-2 rounded-sm bg-accent px-5 text-sm font-bold text-foreground hover:bg-accent/90">{t("ctaJoin")} <ArrowRight className="h-4 w-4" /></Link><Link href="/prices" className="inline-flex h-11 items-center rounded-sm border border-primary-foreground/30 px-5 text-sm font-semibold hover:bg-primary-foreground/10">{t("ctaPrices")}</Link></div></div></section>
    </div>
  );
}